spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/db
    username: root
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db/migration/common

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    root: info