spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
        format_sql: true
        show_sql: false
        highlight_sql: true
#        use_sql_comments: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db/migration/common, db/migration/local

  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      chain:
        cache: false

logging:
  level:
    root: info
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace



